// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2S/C2SEndlessCloisterMsg.proto

package org.game.protobuf.c2s;

public final class C2SEndlessCloisterMsg {
  private C2SEndlessCloisterMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqEndlessCloisterInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.ReqEndlessCloisterInfo}
   *
   * <pre>
   * 取得无尽回廊活动副本信息
   * code = 5377
   * </pre>
   */
  public static final class ReqEndlessCloisterInfo extends
      com.google.protobuf.GeneratedMessage
      implements ReqEndlessCloisterInfoOrBuilder {
    // Use ReqEndlessCloisterInfo.newBuilder() to construct.
    private ReqEndlessCloisterInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqEndlessCloisterInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqEndlessCloisterInfo defaultInstance;
    public static ReqEndlessCloisterInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ReqEndlessCloisterInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqEndlessCloisterInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqEndlessCloisterInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqEndlessCloisterInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo.class, org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqEndlessCloisterInfo> PARSER =
        new com.google.protobuf.AbstractParser<ReqEndlessCloisterInfo>() {
      public ReqEndlessCloisterInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqEndlessCloisterInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqEndlessCloisterInfo> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.ReqEndlessCloisterInfo.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 5377;</code>
       */
      eMsgID(0, 5377),
      ;

      /**
       * <code>eMsgID = 5377;</code>
       */
      public static final int eMsgID_VALUE = 5377;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 5377: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.ReqEndlessCloisterInfo.MsgID)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.ReqEndlessCloisterInfo}
     *
     * <pre>
     * 取得无尽回廊活动副本信息
     * code = 5377
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqEndlessCloisterInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqEndlessCloisterInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo.class, org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqEndlessCloisterInfo_descriptor;
      }

      public org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo build() {
        org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo buildPartial() {
        org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo result = new org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo) {
          return mergeFrom((org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo other) {
        if (other == org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqEndlessCloisterInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.ReqEndlessCloisterInfo)
    }

    static {
      defaultInstance = new ReqEndlessCloisterInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.ReqEndlessCloisterInfo)
  }

  public interface ReqStartFightEndlessOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.ReqStartFightEndless}
   *
   * <pre>
   * 请求开始挑战
   * code = 5378
   * </pre>
   */
  public static final class ReqStartFightEndless extends
      com.google.protobuf.GeneratedMessage
      implements ReqStartFightEndlessOrBuilder {
    // Use ReqStartFightEndless.newBuilder() to construct.
    private ReqStartFightEndless(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqStartFightEndless(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqStartFightEndless defaultInstance;
    public static ReqStartFightEndless getDefaultInstance() {
      return defaultInstance;
    }

    public ReqStartFightEndless getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqStartFightEndless(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqStartFightEndless_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqStartFightEndless_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless.class, org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqStartFightEndless> PARSER =
        new com.google.protobuf.AbstractParser<ReqStartFightEndless>() {
      public ReqStartFightEndless parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqStartFightEndless(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqStartFightEndless> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.ReqStartFightEndless.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 5378;</code>
       */
      eMsgID(0, 5378),
      ;

      /**
       * <code>eMsgID = 5378;</code>
       */
      public static final int eMsgID_VALUE = 5378;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 5378: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.ReqStartFightEndless.MsgID)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.ReqStartFightEndless}
     *
     * <pre>
     * 请求开始挑战
     * code = 5378
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndlessOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqStartFightEndless_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqStartFightEndless_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless.class, org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqStartFightEndless_descriptor;
      }

      public org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless build() {
        org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless buildPartial() {
        org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless result = new org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless) {
          return mergeFrom((org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless other) {
        if (other == org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqStartFightEndless) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.ReqStartFightEndless)
    }

    static {
      defaultInstance = new ReqStartFightEndless(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.ReqStartFightEndless)
  }

  public interface ReqPassStageEndlessOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 levelCid = 1;
    /**
     * <code>required int32 levelCid = 1;</code>
     *
     * <pre>
     *关卡id
     * </pre>
     */
    boolean hasLevelCid();
    /**
     * <code>required int32 levelCid = 1;</code>
     *
     * <pre>
     *关卡id
     * </pre>
     */
    int getLevelCid();

    // required int32 costTime = 2;
    /**
     * <code>required int32 costTime = 2;</code>
     *
     * <pre>
     *耗时（秒）
     * </pre>
     */
    boolean hasCostTime();
    /**
     * <code>required int32 costTime = 2;</code>
     *
     * <pre>
     *耗时（秒）
     * </pre>
     */
    int getCostTime();
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.ReqPassStageEndless}
   *
   * <pre>
   * 通关指定关卡
   * code = 5379
   * </pre>
   */
  public static final class ReqPassStageEndless extends
      com.google.protobuf.GeneratedMessage
      implements ReqPassStageEndlessOrBuilder {
    // Use ReqPassStageEndless.newBuilder() to construct.
    private ReqPassStageEndless(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqPassStageEndless(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqPassStageEndless defaultInstance;
    public static ReqPassStageEndless getDefaultInstance() {
      return defaultInstance;
    }

    public ReqPassStageEndless getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqPassStageEndless(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              levelCid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              costTime_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqPassStageEndless_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqPassStageEndless_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless.class, org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqPassStageEndless> PARSER =
        new com.google.protobuf.AbstractParser<ReqPassStageEndless>() {
      public ReqPassStageEndless parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqPassStageEndless(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqPassStageEndless> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.ReqPassStageEndless.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 5379;</code>
       */
      eMsgID(0, 5379),
      ;

      /**
       * <code>eMsgID = 5379;</code>
       */
      public static final int eMsgID_VALUE = 5379;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 5379: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.ReqPassStageEndless.MsgID)
    }

    private int bitField0_;
    // required int32 levelCid = 1;
    public static final int LEVELCID_FIELD_NUMBER = 1;
    private int levelCid_;
    /**
     * <code>required int32 levelCid = 1;</code>
     *
     * <pre>
     *关卡id
     * </pre>
     */
    public boolean hasLevelCid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 levelCid = 1;</code>
     *
     * <pre>
     *关卡id
     * </pre>
     */
    public int getLevelCid() {
      return levelCid_;
    }

    // required int32 costTime = 2;
    public static final int COSTTIME_FIELD_NUMBER = 2;
    private int costTime_;
    /**
     * <code>required int32 costTime = 2;</code>
     *
     * <pre>
     *耗时（秒）
     * </pre>
     */
    public boolean hasCostTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 costTime = 2;</code>
     *
     * <pre>
     *耗时（秒）
     * </pre>
     */
    public int getCostTime() {
      return costTime_;
    }

    private void initFields() {
      levelCid_ = 0;
      costTime_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasLevelCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCostTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, levelCid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, costTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, levelCid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, costTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.ReqPassStageEndless}
     *
     * <pre>
     * 通关指定关卡
     * code = 5379
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndlessOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqPassStageEndless_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqPassStageEndless_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless.class, org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        levelCid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        costTime_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.internal_static_org_game_protobuf_c2s_ReqPassStageEndless_descriptor;
      }

      public org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless build() {
        org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless buildPartial() {
        org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless result = new org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.levelCid_ = levelCid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.costTime_ = costTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless) {
          return mergeFrom((org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless other) {
        if (other == org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless.getDefaultInstance()) return this;
        if (other.hasLevelCid()) {
          setLevelCid(other.getLevelCid());
        }
        if (other.hasCostTime()) {
          setCostTime(other.getCostTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLevelCid()) {
          
          return false;
        }
        if (!hasCostTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SEndlessCloisterMsg.ReqPassStageEndless) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 levelCid = 1;
      private int levelCid_ ;
      /**
       * <code>required int32 levelCid = 1;</code>
       *
       * <pre>
       *关卡id
       * </pre>
       */
      public boolean hasLevelCid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 levelCid = 1;</code>
       *
       * <pre>
       *关卡id
       * </pre>
       */
      public int getLevelCid() {
        return levelCid_;
      }
      /**
       * <code>required int32 levelCid = 1;</code>
       *
       * <pre>
       *关卡id
       * </pre>
       */
      public Builder setLevelCid(int value) {
        bitField0_ |= 0x00000001;
        levelCid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 levelCid = 1;</code>
       *
       * <pre>
       *关卡id
       * </pre>
       */
      public Builder clearLevelCid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        levelCid_ = 0;
        onChanged();
        return this;
      }

      // required int32 costTime = 2;
      private int costTime_ ;
      /**
       * <code>required int32 costTime = 2;</code>
       *
       * <pre>
       *耗时（秒）
       * </pre>
       */
      public boolean hasCostTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 costTime = 2;</code>
       *
       * <pre>
       *耗时（秒）
       * </pre>
       */
      public int getCostTime() {
        return costTime_;
      }
      /**
       * <code>required int32 costTime = 2;</code>
       *
       * <pre>
       *耗时（秒）
       * </pre>
       */
      public Builder setCostTime(int value) {
        bitField0_ |= 0x00000002;
        costTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 costTime = 2;</code>
       *
       * <pre>
       *耗时（秒）
       * </pre>
       */
      public Builder clearCostTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        costTime_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.ReqPassStageEndless)
    }

    static {
      defaultInstance = new ReqPassStageEndless(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.ReqPassStageEndless)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_ReqEndlessCloisterInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_ReqEndlessCloisterInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_ReqStartFightEndless_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_ReqStartFightEndless_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_ReqPassStageEndless_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_ReqPassStageEndless_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037C2S/C2SEndlessCloisterMsg.proto\022\025org.g" +
      "ame.protobuf.c2s\".\n\026ReqEndlessCloisterIn" +
      "fo\"\024\n\005MsgID\022\013\n\006eMsgID\020\201*\",\n\024ReqStartFigh" +
      "tEndless\"\024\n\005MsgID\022\013\n\006eMsgID\020\202*\"O\n\023ReqPas" +
      "sStageEndless\022\020\n\010levelCid\030\001 \002(\005\022\020\n\010costT" +
      "ime\030\002 \002(\005\"\024\n\005MsgID\022\013\n\006eMsgID\020\203*B\027B\025C2SEn" +
      "dlessCloisterMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_game_protobuf_c2s_ReqEndlessCloisterInfo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_game_protobuf_c2s_ReqEndlessCloisterInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_ReqEndlessCloisterInfo_descriptor,
              new java.lang.String[] { });
          internal_static_org_game_protobuf_c2s_ReqStartFightEndless_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_game_protobuf_c2s_ReqStartFightEndless_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_ReqStartFightEndless_descriptor,
              new java.lang.String[] { });
          internal_static_org_game_protobuf_c2s_ReqPassStageEndless_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_game_protobuf_c2s_ReqPassStageEndless_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_ReqPassStageEndless_descriptor,
              new java.lang.String[] { "LevelCid", "CostTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
