// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2S/C2SItemMsg.proto

package org.game.protobuf.c2s;

public final class C2SItemMsg {
  private C2SItemMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetItemsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.GetItems}
   *
   * <pre>
   * 取得全部物品信息
   * code = 515
   * </pre>
   */
  public static final class GetItems extends
      com.google.protobuf.GeneratedMessage
      implements GetItemsOrBuilder {
    // Use GetItems.newBuilder() to construct.
    private GetItems(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetItems(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetItems defaultInstance;
    public static GetItems getDefaultInstance() {
      return defaultInstance;
    }

    public GetItems getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetItems(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_GetItems_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_GetItems_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SItemMsg.GetItems.class, org.game.protobuf.c2s.C2SItemMsg.GetItems.Builder.class);
    }

    public static com.google.protobuf.Parser<GetItems> PARSER =
        new com.google.protobuf.AbstractParser<GetItems>() {
      public GetItems parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetItems(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetItems> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.GetItems.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 515;</code>
       */
      eMsgID(0, 515),
      ;

      /**
       * <code>eMsgID = 515;</code>
       */
      public static final int eMsgID_VALUE = 515;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 515: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SItemMsg.GetItems.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.GetItems.MsgID)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SItemMsg.GetItems parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.GetItems parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.GetItems parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.GetItems parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.GetItems parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.GetItems parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.GetItems parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.GetItems parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.GetItems parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.GetItems parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SItemMsg.GetItems prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.GetItems}
     *
     * <pre>
     * 取得全部物品信息
     * code = 515
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SItemMsg.GetItemsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_GetItems_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_GetItems_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SItemMsg.GetItems.class, org.game.protobuf.c2s.C2SItemMsg.GetItems.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SItemMsg.GetItems.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_GetItems_descriptor;
      }

      public org.game.protobuf.c2s.C2SItemMsg.GetItems getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SItemMsg.GetItems.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SItemMsg.GetItems build() {
        org.game.protobuf.c2s.C2SItemMsg.GetItems result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SItemMsg.GetItems buildPartial() {
        org.game.protobuf.c2s.C2SItemMsg.GetItems result = new org.game.protobuf.c2s.C2SItemMsg.GetItems(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SItemMsg.GetItems) {
          return mergeFrom((org.game.protobuf.c2s.C2SItemMsg.GetItems)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SItemMsg.GetItems other) {
        if (other == org.game.protobuf.c2s.C2SItemMsg.GetItems.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SItemMsg.GetItems parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SItemMsg.GetItems) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.GetItems)
    }

    static {
      defaultInstance = new GetItems(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.GetItems)
  }

  public interface UseItemOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .org.game.protobuf.c2s.ItemInfo items = 1;
    /**
     * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
     */
    java.util.List<org.game.protobuf.c2s.C2SItemMsg.ItemInfo> 
        getItemsList();
    /**
     * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
     */
    org.game.protobuf.c2s.C2SItemMsg.ItemInfo getItems(int index);
    /**
     * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
     */
    java.util.List<? extends org.game.protobuf.c2s.C2SItemMsg.ItemInfoOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
     */
    org.game.protobuf.c2s.C2SItemMsg.ItemInfoOrBuilder getItemsOrBuilder(
        int index);

    // required string heroId = 2;
    /**
     * <code>required string heroId = 2;</code>
     */
    boolean hasHeroId();
    /**
     * <code>required string heroId = 2;</code>
     */
    java.lang.String getHeroId();
    /**
     * <code>required string heroId = 2;</code>
     */
    com.google.protobuf.ByteString
        getHeroIdBytes();

    // required string roleId = 3;
    /**
     * <code>required string roleId = 3;</code>
     */
    boolean hasRoleId();
    /**
     * <code>required string roleId = 3;</code>
     */
    java.lang.String getRoleId();
    /**
     * <code>required string roleId = 3;</code>
     */
    com.google.protobuf.ByteString
        getRoleIdBytes();

    // repeated int32 customParame = 4;
    /**
     * <code>repeated int32 customParame = 4;</code>
     *
     * <pre>
     *选择性礼包下标
     * </pre>
     */
    java.util.List<java.lang.Integer> getCustomParameList();
    /**
     * <code>repeated int32 customParame = 4;</code>
     *
     * <pre>
     *选择性礼包下标
     * </pre>
     */
    int getCustomParameCount();
    /**
     * <code>repeated int32 customParame = 4;</code>
     *
     * <pre>
     *选择性礼包下标
     * </pre>
     */
    int getCustomParame(int index);
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.UseItem}
   *
   * <pre>
   * 使用物品
   * code = 514
   * </pre>
   */
  public static final class UseItem extends
      com.google.protobuf.GeneratedMessage
      implements UseItemOrBuilder {
    // Use UseItem.newBuilder() to construct.
    private UseItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UseItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UseItem defaultInstance;
    public static UseItem getDefaultInstance() {
      return defaultInstance;
    }

    public UseItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UseItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                items_ = new java.util.ArrayList<org.game.protobuf.c2s.C2SItemMsg.ItemInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(input.readMessage(org.game.protobuf.c2s.C2SItemMsg.ItemInfo.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              heroId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              roleId_ = input.readBytes();
              break;
            }
            case 32: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                customParame_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              customParame_.add(input.readInt32());
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
                customParame_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000008;
              }
              while (input.getBytesUntilLimit() > 0) {
                customParame_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          customParame_ = java.util.Collections.unmodifiableList(customParame_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_UseItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_UseItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SItemMsg.UseItem.class, org.game.protobuf.c2s.C2SItemMsg.UseItem.Builder.class);
    }

    public static com.google.protobuf.Parser<UseItem> PARSER =
        new com.google.protobuf.AbstractParser<UseItem>() {
      public UseItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UseItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UseItem> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.UseItem.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 514;</code>
       */
      eMsgID(0, 514),
      ;

      /**
       * <code>eMsgID = 514;</code>
       */
      public static final int eMsgID_VALUE = 514;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 514: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SItemMsg.UseItem.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.UseItem.MsgID)
    }

    private int bitField0_;
    // repeated .org.game.protobuf.c2s.ItemInfo items = 1;
    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<org.game.protobuf.c2s.C2SItemMsg.ItemInfo> items_;
    /**
     * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
     */
    public java.util.List<org.game.protobuf.c2s.C2SItemMsg.ItemInfo> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
     */
    public java.util.List<? extends org.game.protobuf.c2s.C2SItemMsg.ItemInfoOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
     */
    public org.game.protobuf.c2s.C2SItemMsg.ItemInfo getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
     */
    public org.game.protobuf.c2s.C2SItemMsg.ItemInfoOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    // required string heroId = 2;
    public static final int HEROID_FIELD_NUMBER = 2;
    private java.lang.Object heroId_;
    /**
     * <code>required string heroId = 2;</code>
     */
    public boolean hasHeroId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string heroId = 2;</code>
     */
    public java.lang.String getHeroId() {
      java.lang.Object ref = heroId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          heroId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string heroId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHeroIdBytes() {
      java.lang.Object ref = heroId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        heroId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string roleId = 3;
    public static final int ROLEID_FIELD_NUMBER = 3;
    private java.lang.Object roleId_;
    /**
     * <code>required string roleId = 3;</code>
     */
    public boolean hasRoleId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string roleId = 3;</code>
     */
    public java.lang.String getRoleId() {
      java.lang.Object ref = roleId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          roleId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string roleId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRoleIdBytes() {
      java.lang.Object ref = roleId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        roleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated int32 customParame = 4;
    public static final int CUSTOMPARAME_FIELD_NUMBER = 4;
    private java.util.List<java.lang.Integer> customParame_;
    /**
     * <code>repeated int32 customParame = 4;</code>
     *
     * <pre>
     *选择性礼包下标
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getCustomParameList() {
      return customParame_;
    }
    /**
     * <code>repeated int32 customParame = 4;</code>
     *
     * <pre>
     *选择性礼包下标
     * </pre>
     */
    public int getCustomParameCount() {
      return customParame_.size();
    }
    /**
     * <code>repeated int32 customParame = 4;</code>
     *
     * <pre>
     *选择性礼包下标
     * </pre>
     */
    public int getCustomParame(int index) {
      return customParame_.get(index);
    }

    private void initFields() {
      items_ = java.util.Collections.emptyList();
      heroId_ = "";
      roleId_ = "";
      customParame_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasHeroId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRoleId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, getHeroIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, getRoleIdBytes());
      }
      for (int i = 0; i < customParame_.size(); i++) {
        output.writeInt32(4, customParame_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getHeroIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getRoleIdBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < customParame_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(customParame_.get(i));
        }
        size += dataSize;
        size += 1 * getCustomParameList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SItemMsg.UseItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.UseItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.UseItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.UseItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.UseItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.UseItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.UseItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.UseItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.UseItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.UseItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SItemMsg.UseItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.UseItem}
     *
     * <pre>
     * 使用物品
     * code = 514
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SItemMsg.UseItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_UseItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_UseItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SItemMsg.UseItem.class, org.game.protobuf.c2s.C2SItemMsg.UseItem.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SItemMsg.UseItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        heroId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        roleId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        customParame_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_UseItem_descriptor;
      }

      public org.game.protobuf.c2s.C2SItemMsg.UseItem getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SItemMsg.UseItem.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SItemMsg.UseItem build() {
        org.game.protobuf.c2s.C2SItemMsg.UseItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SItemMsg.UseItem buildPartial() {
        org.game.protobuf.c2s.C2SItemMsg.UseItem result = new org.game.protobuf.c2s.C2SItemMsg.UseItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.heroId_ = heroId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.roleId_ = roleId_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          customParame_ = java.util.Collections.unmodifiableList(customParame_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.customParame_ = customParame_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SItemMsg.UseItem) {
          return mergeFrom((org.game.protobuf.c2s.C2SItemMsg.UseItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SItemMsg.UseItem other) {
        if (other == org.game.protobuf.c2s.C2SItemMsg.UseItem.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        if (other.hasHeroId()) {
          bitField0_ |= 0x00000002;
          heroId_ = other.heroId_;
          onChanged();
        }
        if (other.hasRoleId()) {
          bitField0_ |= 0x00000004;
          roleId_ = other.roleId_;
          onChanged();
        }
        if (!other.customParame_.isEmpty()) {
          if (customParame_.isEmpty()) {
            customParame_ = other.customParame_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureCustomParameIsMutable();
            customParame_.addAll(other.customParame_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeroId()) {
          
          return false;
        }
        if (!hasRoleId()) {
          
          return false;
        }
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SItemMsg.UseItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SItemMsg.UseItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .org.game.protobuf.c2s.ItemInfo items = 1;
      private java.util.List<org.game.protobuf.c2s.C2SItemMsg.ItemInfo> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = new java.util.ArrayList<org.game.protobuf.c2s.C2SItemMsg.ItemInfo>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.game.protobuf.c2s.C2SItemMsg.ItemInfo, org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder, org.game.protobuf.c2s.C2SItemMsg.ItemInfoOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public java.util.List<org.game.protobuf.c2s.C2SItemMsg.ItemInfo> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public org.game.protobuf.c2s.C2SItemMsg.ItemInfo getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public Builder setItems(
          int index, org.game.protobuf.c2s.C2SItemMsg.ItemInfo value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public Builder setItems(
          int index, org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public Builder addItems(org.game.protobuf.c2s.C2SItemMsg.ItemInfo value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public Builder addItems(
          int index, org.game.protobuf.c2s.C2SItemMsg.ItemInfo value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public Builder addItems(
          org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public Builder addItems(
          int index, org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends org.game.protobuf.c2s.C2SItemMsg.ItemInfo> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          super.addAll(values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public org.game.protobuf.c2s.C2SItemMsg.ItemInfoOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public java.util.List<? extends org.game.protobuf.c2s.C2SItemMsg.ItemInfoOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            org.game.protobuf.c2s.C2SItemMsg.ItemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, org.game.protobuf.c2s.C2SItemMsg.ItemInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .org.game.protobuf.c2s.ItemInfo items = 1;</code>
       */
      public java.util.List<org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.game.protobuf.c2s.C2SItemMsg.ItemInfo, org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder, org.game.protobuf.c2s.C2SItemMsg.ItemInfoOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.game.protobuf.c2s.C2SItemMsg.ItemInfo, org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder, org.game.protobuf.c2s.C2SItemMsg.ItemInfoOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }

      // required string heroId = 2;
      private java.lang.Object heroId_ = "";
      /**
       * <code>required string heroId = 2;</code>
       */
      public boolean hasHeroId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string heroId = 2;</code>
       */
      public java.lang.String getHeroId() {
        java.lang.Object ref = heroId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          heroId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string heroId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHeroIdBytes() {
        java.lang.Object ref = heroId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          heroId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string heroId = 2;</code>
       */
      public Builder setHeroId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        heroId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string heroId = 2;</code>
       */
      public Builder clearHeroId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        heroId_ = getDefaultInstance().getHeroId();
        onChanged();
        return this;
      }
      /**
       * <code>required string heroId = 2;</code>
       */
      public Builder setHeroIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        heroId_ = value;
        onChanged();
        return this;
      }

      // required string roleId = 3;
      private java.lang.Object roleId_ = "";
      /**
       * <code>required string roleId = 3;</code>
       */
      public boolean hasRoleId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string roleId = 3;</code>
       */
      public java.lang.String getRoleId() {
        java.lang.Object ref = roleId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          roleId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string roleId = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRoleIdBytes() {
        java.lang.Object ref = roleId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          roleId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string roleId = 3;</code>
       */
      public Builder setRoleId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        roleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string roleId = 3;</code>
       */
      public Builder clearRoleId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        roleId_ = getDefaultInstance().getRoleId();
        onChanged();
        return this;
      }
      /**
       * <code>required string roleId = 3;</code>
       */
      public Builder setRoleIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        roleId_ = value;
        onChanged();
        return this;
      }

      // repeated int32 customParame = 4;
      private java.util.List<java.lang.Integer> customParame_ = java.util.Collections.emptyList();
      private void ensureCustomParameIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          customParame_ = new java.util.ArrayList<java.lang.Integer>(customParame_);
          bitField0_ |= 0x00000008;
         }
      }
      /**
       * <code>repeated int32 customParame = 4;</code>
       *
       * <pre>
       *选择性礼包下标
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getCustomParameList() {
        return java.util.Collections.unmodifiableList(customParame_);
      }
      /**
       * <code>repeated int32 customParame = 4;</code>
       *
       * <pre>
       *选择性礼包下标
       * </pre>
       */
      public int getCustomParameCount() {
        return customParame_.size();
      }
      /**
       * <code>repeated int32 customParame = 4;</code>
       *
       * <pre>
       *选择性礼包下标
       * </pre>
       */
      public int getCustomParame(int index) {
        return customParame_.get(index);
      }
      /**
       * <code>repeated int32 customParame = 4;</code>
       *
       * <pre>
       *选择性礼包下标
       * </pre>
       */
      public Builder setCustomParame(
          int index, int value) {
        ensureCustomParameIsMutable();
        customParame_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 customParame = 4;</code>
       *
       * <pre>
       *选择性礼包下标
       * </pre>
       */
      public Builder addCustomParame(int value) {
        ensureCustomParameIsMutable();
        customParame_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 customParame = 4;</code>
       *
       * <pre>
       *选择性礼包下标
       * </pre>
       */
      public Builder addAllCustomParame(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCustomParameIsMutable();
        super.addAll(values, customParame_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 customParame = 4;</code>
       *
       * <pre>
       *选择性礼包下标
       * </pre>
       */
      public Builder clearCustomParame() {
        customParame_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.UseItem)
    }

    static {
      defaultInstance = new UseItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.UseItem)
  }

  public interface ItemInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string itemId = 1;
    /**
     * <code>required string itemId = 1;</code>
     */
    boolean hasItemId();
    /**
     * <code>required string itemId = 1;</code>
     */
    java.lang.String getItemId();
    /**
     * <code>required string itemId = 1;</code>
     */
    com.google.protobuf.ByteString
        getItemIdBytes();

    // required int32 num = 2;
    /**
     * <code>required int32 num = 2;</code>
     */
    boolean hasNum();
    /**
     * <code>required int32 num = 2;</code>
     */
    int getNum();
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.ItemInfo}
   *
   * <pre>
   * 使用道具
   * </pre>
   */
  public static final class ItemInfo extends
      com.google.protobuf.GeneratedMessage
      implements ItemInfoOrBuilder {
    // Use ItemInfo.newBuilder() to construct.
    private ItemInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ItemInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ItemInfo defaultInstance;
    public static ItemInfo getDefaultInstance() {
      return defaultInstance;
    }

    public ItemInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ItemInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              itemId_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              num_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_ItemInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_ItemInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SItemMsg.ItemInfo.class, org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<ItemInfo> PARSER =
        new com.google.protobuf.AbstractParser<ItemInfo>() {
      public ItemInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ItemInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string itemId = 1;
    public static final int ITEMID_FIELD_NUMBER = 1;
    private java.lang.Object itemId_;
    /**
     * <code>required string itemId = 1;</code>
     */
    public boolean hasItemId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string itemId = 1;</code>
     */
    public java.lang.String getItemId() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          itemId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string itemId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getItemIdBytes() {
      java.lang.Object ref = itemId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        itemId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required int32 num = 2;
    public static final int NUM_FIELD_NUMBER = 2;
    private int num_;
    /**
     * <code>required int32 num = 2;</code>
     */
    public boolean hasNum() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 num = 2;</code>
     */
    public int getNum() {
      return num_;
    }

    private void initFields() {
      itemId_ = "";
      num_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasItemId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getItemIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, num_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getItemIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, num_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SItemMsg.ItemInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.ItemInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.ItemInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.ItemInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.ItemInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.ItemInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.ItemInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.ItemInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.ItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SItemMsg.ItemInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SItemMsg.ItemInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.ItemInfo}
     *
     * <pre>
     * 使用道具
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SItemMsg.ItemInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_ItemInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_ItemInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SItemMsg.ItemInfo.class, org.game.protobuf.c2s.C2SItemMsg.ItemInfo.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SItemMsg.ItemInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        itemId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        num_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SItemMsg.internal_static_org_game_protobuf_c2s_ItemInfo_descriptor;
      }

      public org.game.protobuf.c2s.C2SItemMsg.ItemInfo getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SItemMsg.ItemInfo.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SItemMsg.ItemInfo build() {
        org.game.protobuf.c2s.C2SItemMsg.ItemInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SItemMsg.ItemInfo buildPartial() {
        org.game.protobuf.c2s.C2SItemMsg.ItemInfo result = new org.game.protobuf.c2s.C2SItemMsg.ItemInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.itemId_ = itemId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.num_ = num_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SItemMsg.ItemInfo) {
          return mergeFrom((org.game.protobuf.c2s.C2SItemMsg.ItemInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SItemMsg.ItemInfo other) {
        if (other == org.game.protobuf.c2s.C2SItemMsg.ItemInfo.getDefaultInstance()) return this;
        if (other.hasItemId()) {
          bitField0_ |= 0x00000001;
          itemId_ = other.itemId_;
          onChanged();
        }
        if (other.hasNum()) {
          setNum(other.getNum());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasItemId()) {
          
          return false;
        }
        if (!hasNum()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SItemMsg.ItemInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SItemMsg.ItemInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string itemId = 1;
      private java.lang.Object itemId_ = "";
      /**
       * <code>required string itemId = 1;</code>
       */
      public boolean hasItemId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string itemId = 1;</code>
       */
      public java.lang.String getItemId() {
        java.lang.Object ref = itemId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          itemId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string itemId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getItemIdBytes() {
        java.lang.Object ref = itemId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          itemId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string itemId = 1;</code>
       */
      public Builder setItemId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        itemId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string itemId = 1;</code>
       */
      public Builder clearItemId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        itemId_ = getDefaultInstance().getItemId();
        onChanged();
        return this;
      }
      /**
       * <code>required string itemId = 1;</code>
       */
      public Builder setItemIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        itemId_ = value;
        onChanged();
        return this;
      }

      // required int32 num = 2;
      private int num_ ;
      /**
       * <code>required int32 num = 2;</code>
       */
      public boolean hasNum() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 num = 2;</code>
       */
      public int getNum() {
        return num_;
      }
      /**
       * <code>required int32 num = 2;</code>
       */
      public Builder setNum(int value) {
        bitField0_ |= 0x00000002;
        num_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 num = 2;</code>
       */
      public Builder clearNum() {
        bitField0_ = (bitField0_ & ~0x00000002);
        num_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.ItemInfo)
    }

    static {
      defaultInstance = new ItemInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.ItemInfo)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_GetItems_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_GetItems_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_UseItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_UseItem_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_ItemInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_ItemInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024C2S/C2SItemMsg.proto\022\025org.game.protobu" +
      "f.c2s\" \n\010GetItems\"\024\n\005MsgID\022\013\n\006eMsgID\020\203\004\"" +
      "\205\001\n\007UseItem\022.\n\005items\030\001 \003(\0132\037.org.game.pr" +
      "otobuf.c2s.ItemInfo\022\016\n\006heroId\030\002 \002(\t\022\016\n\006r" +
      "oleId\030\003 \002(\t\022\024\n\014customParame\030\004 \003(\005\"\024\n\005Msg" +
      "ID\022\013\n\006eMsgID\020\202\004\"\'\n\010ItemInfo\022\016\n\006itemId\030\001 " +
      "\002(\t\022\013\n\003num\030\002 \002(\005B\014B\nC2SItemMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_game_protobuf_c2s_GetItems_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_game_protobuf_c2s_GetItems_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_GetItems_descriptor,
              new java.lang.String[] { });
          internal_static_org_game_protobuf_c2s_UseItem_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_game_protobuf_c2s_UseItem_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_UseItem_descriptor,
              new java.lang.String[] { "Items", "HeroId", "RoleId", "CustomParame", });
          internal_static_org_game_protobuf_c2s_ItemInfo_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_game_protobuf_c2s_ItemInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_ItemInfo_descriptor,
              new java.lang.String[] { "ItemId", "Num", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
