// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2S/C2SMailMsg.proto

package org.game.protobuf.c2s;

public final class C2SMailMsg {
  private C2SMailMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code org.game.protobuf.c2s.MailOperationType}
   *
   * <pre>
   * 邮件操作类型
   * </pre>
   */
  public enum MailOperationType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>READ = 1;</code>
     *
     * <pre>
     * 读取
     * </pre>
     */
    READ(0, 1),
    /**
     * <code>RECEIVE = 2;</code>
     *
     * <pre>
     * 收取
     * </pre>
     */
    RECEIVE(1, 2),
    /**
     * <code>DELETE = 3;</code>
     *
     * <pre>
     * 删除
     * </pre>
     */
    DELETE(2, 3),
    ;

    /**
     * <code>READ = 1;</code>
     *
     * <pre>
     * 读取
     * </pre>
     */
    public static final int READ_VALUE = 1;
    /**
     * <code>RECEIVE = 2;</code>
     *
     * <pre>
     * 收取
     * </pre>
     */
    public static final int RECEIVE_VALUE = 2;
    /**
     * <code>DELETE = 3;</code>
     *
     * <pre>
     * 删除
     * </pre>
     */
    public static final int DELETE_VALUE = 3;


    public final int getNumber() { return value; }

    public static MailOperationType valueOf(int value) {
      switch (value) {
        case 1: return READ;
        case 2: return RECEIVE;
        case 3: return DELETE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MailOperationType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<MailOperationType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MailOperationType>() {
            public MailOperationType findValueByNumber(int number) {
              return MailOperationType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SMailMsg.getDescriptor().getEnumTypes().get(0);
    }

    private static final MailOperationType[] VALUES = values();

    public static MailOperationType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private MailOperationType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.MailOperationType)
  }

  public interface MailHandleMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated string ids = 1;
    /**
     * <code>repeated string ids = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    java.util.List<java.lang.String>
    getIdsList();
    /**
     * <code>repeated string ids = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    int getIdsCount();
    /**
     * <code>repeated string ids = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    java.lang.String getIds(int index);
    /**
     * <code>repeated string ids = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdsBytes(int index);

    // required .org.game.protobuf.c2s.MailOperationType type = 2;
    /**
     * <code>required .org.game.protobuf.c2s.MailOperationType type = 2;</code>
     *
     * <pre>
     * 邮件操作类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required .org.game.protobuf.c2s.MailOperationType type = 2;</code>
     *
     * <pre>
     * 邮件操作类型
     * </pre>
     */
    org.game.protobuf.c2s.C2SMailMsg.MailOperationType getType();
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.MailHandleMsg}
   *
   * <pre>
   * 邮件操作
   * code = 769
   * </pre>
   */
  public static final class MailHandleMsg extends
      com.google.protobuf.GeneratedMessage
      implements MailHandleMsgOrBuilder {
    // Use MailHandleMsg.newBuilder() to construct.
    private MailHandleMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MailHandleMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MailHandleMsg defaultInstance;
    public static MailHandleMsg getDefaultInstance() {
      return defaultInstance;
    }

    public MailHandleMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MailHandleMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                ids_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              ids_.add(input.readBytes());
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.game.protobuf.c2s.C2SMailMsg.MailOperationType value = org.game.protobuf.c2s.C2SMailMsg.MailOperationType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = new com.google.protobuf.UnmodifiableLazyStringList(ids_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SMailMsg.internal_static_org_game_protobuf_c2s_MailHandleMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SMailMsg.internal_static_org_game_protobuf_c2s_MailHandleMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg.class, org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<MailHandleMsg> PARSER =
        new com.google.protobuf.AbstractParser<MailHandleMsg>() {
      public MailHandleMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MailHandleMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MailHandleMsg> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.MailHandleMsg.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 769;</code>
       */
      eMsgID(0, 769),
      ;

      /**
       * <code>eMsgID = 769;</code>
       */
      public static final int eMsgID_VALUE = 769;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 769: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.MailHandleMsg.MsgID)
    }

    private int bitField0_;
    // repeated string ids = 1;
    public static final int IDS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList ids_;
    /**
     * <code>repeated string ids = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    public java.util.List<java.lang.String>
        getIdsList() {
      return ids_;
    }
    /**
     * <code>repeated string ids = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    public int getIdsCount() {
      return ids_.size();
    }
    /**
     * <code>repeated string ids = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    public java.lang.String getIds(int index) {
      return ids_.get(index);
    }
    /**
     * <code>repeated string ids = 1;</code>
     *
     * <pre>
     * 邮件ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdsBytes(int index) {
      return ids_.getByteString(index);
    }

    // required .org.game.protobuf.c2s.MailOperationType type = 2;
    public static final int TYPE_FIELD_NUMBER = 2;
    private org.game.protobuf.c2s.C2SMailMsg.MailOperationType type_;
    /**
     * <code>required .org.game.protobuf.c2s.MailOperationType type = 2;</code>
     *
     * <pre>
     * 邮件操作类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .org.game.protobuf.c2s.MailOperationType type = 2;</code>
     *
     * <pre>
     * 邮件操作类型
     * </pre>
     */
    public org.game.protobuf.c2s.C2SMailMsg.MailOperationType getType() {
      return type_;
    }

    private void initFields() {
      ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      type_ = org.game.protobuf.c2s.C2SMailMsg.MailOperationType.READ;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < ids_.size(); i++) {
        output.writeBytes(1, ids_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(2, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < ids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(ids_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getIdsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.MailHandleMsg}
     *
     * <pre>
     * 邮件操作
     * code = 769
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SMailMsg.MailHandleMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SMailMsg.internal_static_org_game_protobuf_c2s_MailHandleMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SMailMsg.internal_static_org_game_protobuf_c2s_MailHandleMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg.class, org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.game.protobuf.c2s.C2SMailMsg.MailOperationType.READ;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SMailMsg.internal_static_org_game_protobuf_c2s_MailHandleMsg_descriptor;
      }

      public org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg build() {
        org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg buildPartial() {
        org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg result = new org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = new com.google.protobuf.UnmodifiableLazyStringList(
              ids_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ids_ = ids_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg) {
          return mergeFrom((org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg other) {
        if (other == org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg.getDefaultInstance()) return this;
        if (!other.ids_.isEmpty()) {
          if (ids_.isEmpty()) {
            ids_ = other.ids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureIdsIsMutable();
            ids_.addAll(other.ids_);
          }
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SMailMsg.MailHandleMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated string ids = 1;
      private com.google.protobuf.LazyStringList ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureIdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          ids_ = new com.google.protobuf.LazyStringArrayList(ids_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string ids = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public java.util.List<java.lang.String>
          getIdsList() {
        return java.util.Collections.unmodifiableList(ids_);
      }
      /**
       * <code>repeated string ids = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public int getIdsCount() {
        return ids_.size();
      }
      /**
       * <code>repeated string ids = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public java.lang.String getIds(int index) {
        return ids_.get(index);
      }
      /**
       * <code>repeated string ids = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdsBytes(int index) {
        return ids_.getByteString(index);
      }
      /**
       * <code>repeated string ids = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public Builder setIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public Builder addIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public Builder addAllIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureIdsIsMutable();
        super.addAll(values, ids_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public Builder clearIds() {
        ids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string ids = 1;</code>
       *
       * <pre>
       * 邮件ID
       * </pre>
       */
      public Builder addIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIdsIsMutable();
        ids_.add(value);
        onChanged();
        return this;
      }

      // required .org.game.protobuf.c2s.MailOperationType type = 2;
      private org.game.protobuf.c2s.C2SMailMsg.MailOperationType type_ = org.game.protobuf.c2s.C2SMailMsg.MailOperationType.READ;
      /**
       * <code>required .org.game.protobuf.c2s.MailOperationType type = 2;</code>
       *
       * <pre>
       * 邮件操作类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .org.game.protobuf.c2s.MailOperationType type = 2;</code>
       *
       * <pre>
       * 邮件操作类型
       * </pre>
       */
      public org.game.protobuf.c2s.C2SMailMsg.MailOperationType getType() {
        return type_;
      }
      /**
       * <code>required .org.game.protobuf.c2s.MailOperationType type = 2;</code>
       *
       * <pre>
       * 邮件操作类型
       * </pre>
       */
      public Builder setType(org.game.protobuf.c2s.C2SMailMsg.MailOperationType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .org.game.protobuf.c2s.MailOperationType type = 2;</code>
       *
       * <pre>
       * 邮件操作类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = org.game.protobuf.c2s.C2SMailMsg.MailOperationType.READ;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.MailHandleMsg)
    }

    static {
      defaultInstance = new MailHandleMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.MailHandleMsg)
  }

  public interface GetMailsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.GetMails}
   *
   * <pre>
   * 取得全部邮件
   * code = 772
   * </pre>
   */
  public static final class GetMails extends
      com.google.protobuf.GeneratedMessage
      implements GetMailsOrBuilder {
    // Use GetMails.newBuilder() to construct.
    private GetMails(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetMails(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetMails defaultInstance;
    public static GetMails getDefaultInstance() {
      return defaultInstance;
    }

    public GetMails getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetMails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SMailMsg.internal_static_org_game_protobuf_c2s_GetMails_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SMailMsg.internal_static_org_game_protobuf_c2s_GetMails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SMailMsg.GetMails.class, org.game.protobuf.c2s.C2SMailMsg.GetMails.Builder.class);
    }

    public static com.google.protobuf.Parser<GetMails> PARSER =
        new com.google.protobuf.AbstractParser<GetMails>() {
      public GetMails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetMails(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetMails> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.GetMails.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 772;</code>
       */
      eMsgID(0, 772),
      ;

      /**
       * <code>eMsgID = 772;</code>
       */
      public static final int eMsgID_VALUE = 772;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 772: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SMailMsg.GetMails.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.GetMails.MsgID)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SMailMsg.GetMails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.GetMails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.GetMails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.GetMails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.GetMails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.GetMails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.GetMails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.GetMails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.GetMails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SMailMsg.GetMails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SMailMsg.GetMails prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.GetMails}
     *
     * <pre>
     * 取得全部邮件
     * code = 772
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SMailMsg.GetMailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SMailMsg.internal_static_org_game_protobuf_c2s_GetMails_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SMailMsg.internal_static_org_game_protobuf_c2s_GetMails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SMailMsg.GetMails.class, org.game.protobuf.c2s.C2SMailMsg.GetMails.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SMailMsg.GetMails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SMailMsg.internal_static_org_game_protobuf_c2s_GetMails_descriptor;
      }

      public org.game.protobuf.c2s.C2SMailMsg.GetMails getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SMailMsg.GetMails.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SMailMsg.GetMails build() {
        org.game.protobuf.c2s.C2SMailMsg.GetMails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SMailMsg.GetMails buildPartial() {
        org.game.protobuf.c2s.C2SMailMsg.GetMails result = new org.game.protobuf.c2s.C2SMailMsg.GetMails(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SMailMsg.GetMails) {
          return mergeFrom((org.game.protobuf.c2s.C2SMailMsg.GetMails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SMailMsg.GetMails other) {
        if (other == org.game.protobuf.c2s.C2SMailMsg.GetMails.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SMailMsg.GetMails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SMailMsg.GetMails) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.GetMails)
    }

    static {
      defaultInstance = new GetMails(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.GetMails)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_MailHandleMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_MailHandleMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_GetMails_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_GetMails_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024C2S/C2SMailMsg.proto\022\025org.game.protobu" +
      "f.c2s\"j\n\rMailHandleMsg\022\013\n\003ids\030\001 \003(\t\0226\n\004t" +
      "ype\030\002 \002(\0162(.org.game.protobuf.c2s.MailOp" +
      "erationType\"\024\n\005MsgID\022\013\n\006eMsgID\020\201\006\" \n\010Get" +
      "Mails\"\024\n\005MsgID\022\013\n\006eMsgID\020\204\006*6\n\021MailOpera" +
      "tionType\022\010\n\004READ\020\001\022\013\n\007RECEIVE\020\002\022\n\n\006DELET" +
      "E\020\003B\014B\nC2SMailMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_game_protobuf_c2s_MailHandleMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_game_protobuf_c2s_MailHandleMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_MailHandleMsg_descriptor,
              new java.lang.String[] { "Ids", "Type", });
          internal_static_org_game_protobuf_c2s_GetMails_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_game_protobuf_c2s_GetMails_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_GetMails_descriptor,
              new java.lang.String[] { });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
