// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2S/C2SSummonMsg.proto

package org.game.protobuf.c2s;

public final class C2SSummonMsg {
  private C2SSummonMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SummonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cid = 1;
    /**
     * <code>required int32 cid = 1;</code>
     *
     * <pre>
     *召唤id
     * </pre>
     */
    boolean hasCid();
    /**
     * <code>required int32 cid = 1;</code>
     *
     * <pre>
     *召唤id
     * </pre>
     */
    int getCid();

    // optional int32 cost = 2;
    /**
     * <code>optional int32 cost = 2;</code>
     *
     * <pre>
     *消耗
     * </pre>
     */
    boolean hasCost();
    /**
     * <code>optional int32 cost = 2;</code>
     *
     * <pre>
     *消耗
     * </pre>
     */
    int getCost();
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.Summon}
   *
   * <pre>
   *召唤
   *code = 3329
   * </pre>
   */
  public static final class Summon extends
      com.google.protobuf.GeneratedMessage
      implements SummonOrBuilder {
    // Use Summon.newBuilder() to construct.
    private Summon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Summon(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Summon defaultInstance;
    public static Summon getDefaultInstance() {
      return defaultInstance;
    }

    public Summon getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Summon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              cost_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_Summon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_Summon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SSummonMsg.Summon.class, org.game.protobuf.c2s.C2SSummonMsg.Summon.Builder.class);
    }

    public static com.google.protobuf.Parser<Summon> PARSER =
        new com.google.protobuf.AbstractParser<Summon>() {
      public Summon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Summon(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Summon> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.Summon.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 3329;</code>
       */
      eMsgID(0, 3329),
      ;

      /**
       * <code>eMsgID = 3329;</code>
       */
      public static final int eMsgID_VALUE = 3329;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 3329: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SSummonMsg.Summon.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.Summon.MsgID)
    }

    private int bitField0_;
    // required int32 cid = 1;
    public static final int CID_FIELD_NUMBER = 1;
    private int cid_;
    /**
     * <code>required int32 cid = 1;</code>
     *
     * <pre>
     *召唤id
     * </pre>
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cid = 1;</code>
     *
     * <pre>
     *召唤id
     * </pre>
     */
    public int getCid() {
      return cid_;
    }

    // optional int32 cost = 2;
    public static final int COST_FIELD_NUMBER = 2;
    private int cost_;
    /**
     * <code>optional int32 cost = 2;</code>
     *
     * <pre>
     *消耗
     * </pre>
     */
    public boolean hasCost() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 cost = 2;</code>
     *
     * <pre>
     *消耗
     * </pre>
     */
    public int getCost() {
      return cost_;
    }

    private void initFields() {
      cid_ = 0;
      cost_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, cost_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, cost_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SSummonMsg.Summon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.Summon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.Summon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.Summon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.Summon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.Summon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.Summon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.Summon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.Summon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.Summon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SSummonMsg.Summon prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.Summon}
     *
     * <pre>
     *召唤
     *code = 3329
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SSummonMsg.SummonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_Summon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_Summon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SSummonMsg.Summon.class, org.game.protobuf.c2s.C2SSummonMsg.Summon.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SSummonMsg.Summon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        cost_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_Summon_descriptor;
      }

      public org.game.protobuf.c2s.C2SSummonMsg.Summon getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SSummonMsg.Summon.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SSummonMsg.Summon build() {
        org.game.protobuf.c2s.C2SSummonMsg.Summon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SSummonMsg.Summon buildPartial() {
        org.game.protobuf.c2s.C2SSummonMsg.Summon result = new org.game.protobuf.c2s.C2SSummonMsg.Summon(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cid_ = cid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cost_ = cost_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SSummonMsg.Summon) {
          return mergeFrom((org.game.protobuf.c2s.C2SSummonMsg.Summon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SSummonMsg.Summon other) {
        if (other == org.game.protobuf.c2s.C2SSummonMsg.Summon.getDefaultInstance()) return this;
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        if (other.hasCost()) {
          setCost(other.getCost());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SSummonMsg.Summon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SSummonMsg.Summon) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cid = 1;
      private int cid_ ;
      /**
       * <code>required int32 cid = 1;</code>
       *
       * <pre>
       *召唤id
       * </pre>
       */
      public boolean hasCid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cid = 1;</code>
       *
       * <pre>
       *召唤id
       * </pre>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>required int32 cid = 1;</code>
       *
       * <pre>
       *召唤id
       * </pre>
       */
      public Builder setCid(int value) {
        bitField0_ |= 0x00000001;
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cid = 1;</code>
       *
       * <pre>
       *召唤id
       * </pre>
       */
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = 0;
        onChanged();
        return this;
      }

      // optional int32 cost = 2;
      private int cost_ ;
      /**
       * <code>optional int32 cost = 2;</code>
       *
       * <pre>
       *消耗
       * </pre>
       */
      public boolean hasCost() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 cost = 2;</code>
       *
       * <pre>
       *消耗
       * </pre>
       */
      public int getCost() {
        return cost_;
      }
      /**
       * <code>optional int32 cost = 2;</code>
       *
       * <pre>
       *消耗
       * </pre>
       */
      public Builder setCost(int value) {
        bitField0_ |= 0x00000002;
        cost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cost = 2;</code>
       *
       * <pre>
       *消耗
       * </pre>
       */
      public Builder clearCost() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cost_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.Summon)
    }

    static {
      defaultInstance = new Summon(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.Summon)
  }

  public interface ComposeSummonOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 cid = 1;
    /**
     * <code>required int32 cid = 1;</code>
     *
     * <pre>
     *合成召唤id
     * </pre>
     */
    boolean hasCid();
    /**
     * <code>required int32 cid = 1;</code>
     *
     * <pre>
     *合成召唤id
     * </pre>
     */
    int getCid();
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.ComposeSummon}
   *
   * <pre>
   *合成
   *code = 3330
   * </pre>
   */
  public static final class ComposeSummon extends
      com.google.protobuf.GeneratedMessage
      implements ComposeSummonOrBuilder {
    // Use ComposeSummon.newBuilder() to construct.
    private ComposeSummon(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ComposeSummon(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ComposeSummon defaultInstance;
    public static ComposeSummon getDefaultInstance() {
      return defaultInstance;
    }

    public ComposeSummon getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ComposeSummon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ComposeSummon_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ComposeSummon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon.class, org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon.Builder.class);
    }

    public static com.google.protobuf.Parser<ComposeSummon> PARSER =
        new com.google.protobuf.AbstractParser<ComposeSummon>() {
      public ComposeSummon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComposeSummon(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ComposeSummon> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.ComposeSummon.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 3330;</code>
       */
      eMsgID(0, 3330),
      ;

      /**
       * <code>eMsgID = 3330;</code>
       */
      public static final int eMsgID_VALUE = 3330;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 3330: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.ComposeSummon.MsgID)
    }

    private int bitField0_;
    // required int32 cid = 1;
    public static final int CID_FIELD_NUMBER = 1;
    private int cid_;
    /**
     * <code>required int32 cid = 1;</code>
     *
     * <pre>
     *合成召唤id
     * </pre>
     */
    public boolean hasCid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 cid = 1;</code>
     *
     * <pre>
     *合成召唤id
     * </pre>
     */
    public int getCid() {
      return cid_;
    }

    private void initFields() {
      cid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.ComposeSummon}
     *
     * <pre>
     *合成
     *code = 3330
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SSummonMsg.ComposeSummonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ComposeSummon_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ComposeSummon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon.class, org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        cid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ComposeSummon_descriptor;
      }

      public org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon build() {
        org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon buildPartial() {
        org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon result = new org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cid_ = cid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon) {
          return mergeFrom((org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon other) {
        if (other == org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon.getDefaultInstance()) return this;
        if (other.hasCid()) {
          setCid(other.getCid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasCid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SSummonMsg.ComposeSummon) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 cid = 1;
      private int cid_ ;
      /**
       * <code>required int32 cid = 1;</code>
       *
       * <pre>
       *合成召唤id
       * </pre>
       */
      public boolean hasCid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 cid = 1;</code>
       *
       * <pre>
       *合成召唤id
       * </pre>
       */
      public int getCid() {
        return cid_;
      }
      /**
       * <code>required int32 cid = 1;</code>
       *
       * <pre>
       *合成召唤id
       * </pre>
       */
      public Builder setCid(int value) {
        bitField0_ |= 0x00000001;
        cid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 cid = 1;</code>
       *
       * <pre>
       *合成召唤id
       * </pre>
       */
      public Builder clearCid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cid_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.ComposeSummon)
    }

    static {
      defaultInstance = new ComposeSummon(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.ComposeSummon)
  }

  public interface ComposeFinishOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 zPointType = 1;
    /**
     * <code>required int32 zPointType = 1;</code>
     *
     * <pre>
     *质点类型
     * </pre>
     */
    boolean hasZPointType();
    /**
     * <code>required int32 zPointType = 1;</code>
     *
     * <pre>
     *质点类型
     * </pre>
     */
    int getZPointType();
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.ComposeFinish}
   *
   * <pre>
   *合成完成
   *code = 3331
   * </pre>
   */
  public static final class ComposeFinish extends
      com.google.protobuf.GeneratedMessage
      implements ComposeFinishOrBuilder {
    // Use ComposeFinish.newBuilder() to construct.
    private ComposeFinish(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ComposeFinish(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ComposeFinish defaultInstance;
    public static ComposeFinish getDefaultInstance() {
      return defaultInstance;
    }

    public ComposeFinish getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ComposeFinish(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              zPointType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ComposeFinish_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ComposeFinish_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish.class, org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish.Builder.class);
    }

    public static com.google.protobuf.Parser<ComposeFinish> PARSER =
        new com.google.protobuf.AbstractParser<ComposeFinish>() {
      public ComposeFinish parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComposeFinish(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ComposeFinish> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.ComposeFinish.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 3331;</code>
       */
      eMsgID(0, 3331),
      ;

      /**
       * <code>eMsgID = 3331;</code>
       */
      public static final int eMsgID_VALUE = 3331;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 3331: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.ComposeFinish.MsgID)
    }

    private int bitField0_;
    // required int32 zPointType = 1;
    public static final int ZPOINTTYPE_FIELD_NUMBER = 1;
    private int zPointType_;
    /**
     * <code>required int32 zPointType = 1;</code>
     *
     * <pre>
     *质点类型
     * </pre>
     */
    public boolean hasZPointType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 zPointType = 1;</code>
     *
     * <pre>
     *质点类型
     * </pre>
     */
    public int getZPointType() {
      return zPointType_;
    }

    private void initFields() {
      zPointType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasZPointType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, zPointType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, zPointType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.ComposeFinish}
     *
     * <pre>
     *合成完成
     *code = 3331
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SSummonMsg.ComposeFinishOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ComposeFinish_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ComposeFinish_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish.class, org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        zPointType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ComposeFinish_descriptor;
      }

      public org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish build() {
        org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish buildPartial() {
        org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish result = new org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.zPointType_ = zPointType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish) {
          return mergeFrom((org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish other) {
        if (other == org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish.getDefaultInstance()) return this;
        if (other.hasZPointType()) {
          setZPointType(other.getZPointType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasZPointType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SSummonMsg.ComposeFinish) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 zPointType = 1;
      private int zPointType_ ;
      /**
       * <code>required int32 zPointType = 1;</code>
       *
       * <pre>
       *质点类型
       * </pre>
       */
      public boolean hasZPointType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 zPointType = 1;</code>
       *
       * <pre>
       *质点类型
       * </pre>
       */
      public int getZPointType() {
        return zPointType_;
      }
      /**
       * <code>required int32 zPointType = 1;</code>
       *
       * <pre>
       *质点类型
       * </pre>
       */
      public Builder setZPointType(int value) {
        bitField0_ |= 0x00000001;
        zPointType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 zPointType = 1;</code>
       *
       * <pre>
       *质点类型
       * </pre>
       */
      public Builder clearZPointType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        zPointType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.ComposeFinish)
    }

    static {
      defaultInstance = new ComposeFinish(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.ComposeFinish)
  }

  public interface GetComposeInfoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.GetComposeInfo}
   *
   * <pre>
   *获取完成信息
   *code = 3333
   * </pre>
   */
  public static final class GetComposeInfo extends
      com.google.protobuf.GeneratedMessage
      implements GetComposeInfoOrBuilder {
    // Use GetComposeInfo.newBuilder() to construct.
    private GetComposeInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private GetComposeInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final GetComposeInfo defaultInstance;
    public static GetComposeInfo getDefaultInstance() {
      return defaultInstance;
    }

    public GetComposeInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private GetComposeInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_GetComposeInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_GetComposeInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo.class, org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<GetComposeInfo> PARSER =
        new com.google.protobuf.AbstractParser<GetComposeInfo>() {
      public GetComposeInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GetComposeInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<GetComposeInfo> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.GetComposeInfo.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 3333;</code>
       */
      eMsgID(0, 3333),
      ;

      /**
       * <code>eMsgID = 3333;</code>
       */
      public static final int eMsgID_VALUE = 3333;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 3333: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.GetComposeInfo.MsgID)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.GetComposeInfo}
     *
     * <pre>
     *获取完成信息
     *code = 3333
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_GetComposeInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_GetComposeInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo.class, org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_GetComposeInfo_descriptor;
      }

      public org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo build() {
        org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo buildPartial() {
        org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo result = new org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo) {
          return mergeFrom((org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo other) {
        if (other == org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SSummonMsg.GetComposeInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.GetComposeInfo)
    }

    static {
      defaultInstance = new GetComposeInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.GetComposeInfo)
  }

  public interface ReqHistoryRecordOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated int32 type = 1;
    /**
     * <code>repeated int32 type = 1;</code>
     *
     * <pre>
     * 1 钻石召唤 2 友情召唤 3 指定召唤
     * </pre>
     */
    java.util.List<java.lang.Integer> getTypeList();
    /**
     * <code>repeated int32 type = 1;</code>
     *
     * <pre>
     * 1 钻石召唤 2 友情召唤 3 指定召唤
     * </pre>
     */
    int getTypeCount();
    /**
     * <code>repeated int32 type = 1;</code>
     *
     * <pre>
     * 1 钻石召唤 2 友情召唤 3 指定召唤
     * </pre>
     */
    int getType(int index);
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.ReqHistoryRecord}
   *
   * <pre>
   *请求获取历史记录
   *code = 3335
   * </pre>
   */
  public static final class ReqHistoryRecord extends
      com.google.protobuf.GeneratedMessage
      implements ReqHistoryRecordOrBuilder {
    // Use ReqHistoryRecord.newBuilder() to construct.
    private ReqHistoryRecord(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqHistoryRecord(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqHistoryRecord defaultInstance;
    public static ReqHistoryRecord getDefaultInstance() {
      return defaultInstance;
    }

    public ReqHistoryRecord getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqHistoryRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                type_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              type_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                type_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                type_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          type_ = java.util.Collections.unmodifiableList(type_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ReqHistoryRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ReqHistoryRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord.class, org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqHistoryRecord> PARSER =
        new com.google.protobuf.AbstractParser<ReqHistoryRecord>() {
      public ReqHistoryRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqHistoryRecord(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqHistoryRecord> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.ReqHistoryRecord.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 3335;</code>
       */
      eMsgID(0, 3335),
      ;

      /**
       * <code>eMsgID = 3335;</code>
       */
      public static final int eMsgID_VALUE = 3335;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 3335: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.ReqHistoryRecord.MsgID)
    }

    // repeated int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> type_;
    /**
     * <code>repeated int32 type = 1;</code>
     *
     * <pre>
     * 1 钻石召唤 2 友情召唤 3 指定召唤
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getTypeList() {
      return type_;
    }
    /**
     * <code>repeated int32 type = 1;</code>
     *
     * <pre>
     * 1 钻石召唤 2 友情召唤 3 指定召唤
     * </pre>
     */
    public int getTypeCount() {
      return type_.size();
    }
    /**
     * <code>repeated int32 type = 1;</code>
     *
     * <pre>
     * 1 钻石召唤 2 友情召唤 3 指定召唤
     * </pre>
     */
    public int getType(int index) {
      return type_.get(index);
    }

    private void initFields() {
      type_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < type_.size(); i++) {
        output.writeInt32(1, type_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < type_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(type_.get(i));
        }
        size += dataSize;
        size += 1 * getTypeList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.ReqHistoryRecord}
     *
     * <pre>
     *请求获取历史记录
     *code = 3335
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ReqHistoryRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ReqHistoryRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord.class, org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2SSummonMsg.internal_static_org_game_protobuf_c2s_ReqHistoryRecord_descriptor;
      }

      public org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord build() {
        org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord buildPartial() {
        org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord result = new org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          type_ = java.util.Collections.unmodifiableList(type_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord) {
          return mergeFrom((org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord other) {
        if (other == org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord.getDefaultInstance()) return this;
        if (!other.type_.isEmpty()) {
          if (type_.isEmpty()) {
            type_ = other.type_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTypeIsMutable();
            type_.addAll(other.type_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2SSummonMsg.ReqHistoryRecord) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated int32 type = 1;
      private java.util.List<java.lang.Integer> type_ = java.util.Collections.emptyList();
      private void ensureTypeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          type_ = new java.util.ArrayList<java.lang.Integer>(type_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 type = 1;</code>
       *
       * <pre>
       * 1 钻石召唤 2 友情召唤 3 指定召唤
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getTypeList() {
        return java.util.Collections.unmodifiableList(type_);
      }
      /**
       * <code>repeated int32 type = 1;</code>
       *
       * <pre>
       * 1 钻石召唤 2 友情召唤 3 指定召唤
       * </pre>
       */
      public int getTypeCount() {
        return type_.size();
      }
      /**
       * <code>repeated int32 type = 1;</code>
       *
       * <pre>
       * 1 钻石召唤 2 友情召唤 3 指定召唤
       * </pre>
       */
      public int getType(int index) {
        return type_.get(index);
      }
      /**
       * <code>repeated int32 type = 1;</code>
       *
       * <pre>
       * 1 钻石召唤 2 友情召唤 3 指定召唤
       * </pre>
       */
      public Builder setType(
          int index, int value) {
        ensureTypeIsMutable();
        type_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 type = 1;</code>
       *
       * <pre>
       * 1 钻石召唤 2 友情召唤 3 指定召唤
       * </pre>
       */
      public Builder addType(int value) {
        ensureTypeIsMutable();
        type_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 type = 1;</code>
       *
       * <pre>
       * 1 钻石召唤 2 友情召唤 3 指定召唤
       * </pre>
       */
      public Builder addAllType(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureTypeIsMutable();
        super.addAll(values, type_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 type = 1;</code>
       *
       * <pre>
       * 1 钻石召唤 2 友情召唤 3 指定召唤
       * </pre>
       */
      public Builder clearType() {
        type_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.ReqHistoryRecord)
    }

    static {
      defaultInstance = new ReqHistoryRecord(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.ReqHistoryRecord)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_Summon_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_Summon_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_ComposeSummon_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_ComposeSummon_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_ComposeFinish_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_ComposeFinish_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_GetComposeInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_GetComposeInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_ReqHistoryRecord_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_ReqHistoryRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026C2S/C2SSummonMsg.proto\022\025org.game.proto" +
      "buf.c2s\"9\n\006Summon\022\013\n\003cid\030\001 \002(\005\022\014\n\004cost\030\002" +
      " \001(\005\"\024\n\005MsgID\022\013\n\006eMsgID\020\201\032\"2\n\rComposeSum" +
      "mon\022\013\n\003cid\030\001 \002(\005\"\024\n\005MsgID\022\013\n\006eMsgID\020\202\032\"9" +
      "\n\rComposeFinish\022\022\n\nzPointType\030\001 \002(\005\"\024\n\005M" +
      "sgID\022\013\n\006eMsgID\020\203\032\"&\n\016GetComposeInfo\"\024\n\005M" +
      "sgID\022\013\n\006eMsgID\020\205\032\"6\n\020ReqHistoryRecord\022\014\n" +
      "\004type\030\001 \003(\005\"\024\n\005MsgID\022\013\n\006eMsgID\020\207\032B\016B\014C2S" +
      "SummonMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_game_protobuf_c2s_Summon_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_game_protobuf_c2s_Summon_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_Summon_descriptor,
              new java.lang.String[] { "Cid", "Cost", });
          internal_static_org_game_protobuf_c2s_ComposeSummon_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_game_protobuf_c2s_ComposeSummon_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_ComposeSummon_descriptor,
              new java.lang.String[] { "Cid", });
          internal_static_org_game_protobuf_c2s_ComposeFinish_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_org_game_protobuf_c2s_ComposeFinish_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_ComposeFinish_descriptor,
              new java.lang.String[] { "ZPointType", });
          internal_static_org_game_protobuf_c2s_GetComposeInfo_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_org_game_protobuf_c2s_GetComposeInfo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_GetComposeInfo_descriptor,
              new java.lang.String[] { });
          internal_static_org_game_protobuf_c2s_ReqHistoryRecord_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_org_game_protobuf_c2s_ReqHistoryRecord_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_ReqHistoryRecord_descriptor,
              new java.lang.String[] { "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
