// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: C2S/C2STaskMsg.proto

package org.game.protobuf.c2s;

public final class C2STaskMsg {
  private C2STaskMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqTasksOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.ReqTasks}
   *
   * <pre>
   * 取得所有任务信息
   * code = 4097
   * </pre>
   */
  public static final class ReqTasks extends
      com.google.protobuf.GeneratedMessage
      implements ReqTasksOrBuilder {
    // Use ReqTasks.newBuilder() to construct.
    private ReqTasks(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqTasks(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqTasks defaultInstance;
    public static ReqTasks getDefaultInstance() {
      return defaultInstance;
    }

    public ReqTasks getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqTasks(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2STaskMsg.internal_static_org_game_protobuf_c2s_ReqTasks_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2STaskMsg.internal_static_org_game_protobuf_c2s_ReqTasks_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2STaskMsg.ReqTasks.class, org.game.protobuf.c2s.C2STaskMsg.ReqTasks.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqTasks> PARSER =
        new com.google.protobuf.AbstractParser<ReqTasks>() {
      public ReqTasks parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqTasks(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqTasks> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.ReqTasks.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 4097;</code>
       */
      eMsgID(0, 4097),
      ;

      /**
       * <code>eMsgID = 4097;</code>
       */
      public static final int eMsgID_VALUE = 4097;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 4097: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2STaskMsg.ReqTasks.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.ReqTasks.MsgID)
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2STaskMsg.ReqTasks parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.ReqTasks parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.ReqTasks parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.ReqTasks parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.ReqTasks parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.ReqTasks parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.ReqTasks parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.ReqTasks parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.ReqTasks parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.ReqTasks parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2STaskMsg.ReqTasks prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.ReqTasks}
     *
     * <pre>
     * 取得所有任务信息
     * code = 4097
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2STaskMsg.ReqTasksOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2STaskMsg.internal_static_org_game_protobuf_c2s_ReqTasks_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2STaskMsg.internal_static_org_game_protobuf_c2s_ReqTasks_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2STaskMsg.ReqTasks.class, org.game.protobuf.c2s.C2STaskMsg.ReqTasks.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2STaskMsg.ReqTasks.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2STaskMsg.internal_static_org_game_protobuf_c2s_ReqTasks_descriptor;
      }

      public org.game.protobuf.c2s.C2STaskMsg.ReqTasks getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2STaskMsg.ReqTasks.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2STaskMsg.ReqTasks build() {
        org.game.protobuf.c2s.C2STaskMsg.ReqTasks result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2STaskMsg.ReqTasks buildPartial() {
        org.game.protobuf.c2s.C2STaskMsg.ReqTasks result = new org.game.protobuf.c2s.C2STaskMsg.ReqTasks(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2STaskMsg.ReqTasks) {
          return mergeFrom((org.game.protobuf.c2s.C2STaskMsg.ReqTasks)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2STaskMsg.ReqTasks other) {
        if (other == org.game.protobuf.c2s.C2STaskMsg.ReqTasks.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2STaskMsg.ReqTasks parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2STaskMsg.ReqTasks) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.ReqTasks)
    }

    static {
      defaultInstance = new ReqTasks(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.ReqTasks)
  }

  public interface SubmitTaskOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 taskCid = 1;
    /**
     * <code>required int32 taskCid = 1;</code>
     */
    boolean hasTaskCid();
    /**
     * <code>required int32 taskCid = 1;</code>
     */
    int getTaskCid();
  }
  /**
   * Protobuf type {@code org.game.protobuf.c2s.SubmitTask}
   *
   * <pre>
   * 提交任务
   * code = 4098
   * </pre>
   */
  public static final class SubmitTask extends
      com.google.protobuf.GeneratedMessage
      implements SubmitTaskOrBuilder {
    // Use SubmitTask.newBuilder() to construct.
    private SubmitTask(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SubmitTask(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SubmitTask defaultInstance;
    public static SubmitTask getDefaultInstance() {
      return defaultInstance;
    }

    public SubmitTask getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SubmitTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              taskCid_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.c2s.C2STaskMsg.internal_static_org_game_protobuf_c2s_SubmitTask_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.c2s.C2STaskMsg.internal_static_org_game_protobuf_c2s_SubmitTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.c2s.C2STaskMsg.SubmitTask.class, org.game.protobuf.c2s.C2STaskMsg.SubmitTask.Builder.class);
    }

    public static com.google.protobuf.Parser<SubmitTask> PARSER =
        new com.google.protobuf.AbstractParser<SubmitTask>() {
      public SubmitTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SubmitTask(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SubmitTask> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code org.game.protobuf.c2s.SubmitTask.MsgID}
     */
    public enum MsgID
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>eMsgID = 4098;</code>
       */
      eMsgID(0, 4098),
      ;

      /**
       * <code>eMsgID = 4098;</code>
       */
      public static final int eMsgID_VALUE = 4098;


      public final int getNumber() { return value; }

      public static MsgID valueOf(int value) {
        switch (value) {
          case 4098: return eMsgID;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MsgID>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MsgID>() {
              public MsgID findValueByNumber(int number) {
                return MsgID.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2STaskMsg.SubmitTask.getDescriptor().getEnumTypes().get(0);
      }

      private static final MsgID[] VALUES = values();

      public static MsgID valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private MsgID(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:org.game.protobuf.c2s.SubmitTask.MsgID)
    }

    private int bitField0_;
    // required int32 taskCid = 1;
    public static final int TASKCID_FIELD_NUMBER = 1;
    private int taskCid_;
    /**
     * <code>required int32 taskCid = 1;</code>
     */
    public boolean hasTaskCid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 taskCid = 1;</code>
     */
    public int getTaskCid() {
      return taskCid_;
    }

    private void initFields() {
      taskCid_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTaskCid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, taskCid_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, taskCid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.c2s.C2STaskMsg.SubmitTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.SubmitTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.SubmitTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.SubmitTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.SubmitTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.SubmitTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.SubmitTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.SubmitTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.SubmitTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.c2s.C2STaskMsg.SubmitTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.c2s.C2STaskMsg.SubmitTask prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.c2s.SubmitTask}
     *
     * <pre>
     * 提交任务
     * code = 4098
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.c2s.C2STaskMsg.SubmitTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.c2s.C2STaskMsg.internal_static_org_game_protobuf_c2s_SubmitTask_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.c2s.C2STaskMsg.internal_static_org_game_protobuf_c2s_SubmitTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.c2s.C2STaskMsg.SubmitTask.class, org.game.protobuf.c2s.C2STaskMsg.SubmitTask.Builder.class);
      }

      // Construct using org.game.protobuf.c2s.C2STaskMsg.SubmitTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        taskCid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.c2s.C2STaskMsg.internal_static_org_game_protobuf_c2s_SubmitTask_descriptor;
      }

      public org.game.protobuf.c2s.C2STaskMsg.SubmitTask getDefaultInstanceForType() {
        return org.game.protobuf.c2s.C2STaskMsg.SubmitTask.getDefaultInstance();
      }

      public org.game.protobuf.c2s.C2STaskMsg.SubmitTask build() {
        org.game.protobuf.c2s.C2STaskMsg.SubmitTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.c2s.C2STaskMsg.SubmitTask buildPartial() {
        org.game.protobuf.c2s.C2STaskMsg.SubmitTask result = new org.game.protobuf.c2s.C2STaskMsg.SubmitTask(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskCid_ = taskCid_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.c2s.C2STaskMsg.SubmitTask) {
          return mergeFrom((org.game.protobuf.c2s.C2STaskMsg.SubmitTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.c2s.C2STaskMsg.SubmitTask other) {
        if (other == org.game.protobuf.c2s.C2STaskMsg.SubmitTask.getDefaultInstance()) return this;
        if (other.hasTaskCid()) {
          setTaskCid(other.getTaskCid());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTaskCid()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.c2s.C2STaskMsg.SubmitTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.c2s.C2STaskMsg.SubmitTask) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 taskCid = 1;
      private int taskCid_ ;
      /**
       * <code>required int32 taskCid = 1;</code>
       */
      public boolean hasTaskCid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 taskCid = 1;</code>
       */
      public int getTaskCid() {
        return taskCid_;
      }
      /**
       * <code>required int32 taskCid = 1;</code>
       */
      public Builder setTaskCid(int value) {
        bitField0_ |= 0x00000001;
        taskCid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 taskCid = 1;</code>
       */
      public Builder clearTaskCid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskCid_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.c2s.SubmitTask)
    }

    static {
      defaultInstance = new SubmitTask(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.c2s.SubmitTask)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_ReqTasks_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_ReqTasks_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_c2s_SubmitTask_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_c2s_SubmitTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024C2S/C2STaskMsg.proto\022\025org.game.protobu" +
      "f.c2s\" \n\010ReqTasks\"\024\n\005MsgID\022\013\n\006eMsgID\020\201 \"" +
      "3\n\nSubmitTask\022\017\n\007taskCid\030\001 \002(\005\"\024\n\005MsgID\022" +
      "\013\n\006eMsgID\020\202 B\014B\nC2STaskMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_game_protobuf_c2s_ReqTasks_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_game_protobuf_c2s_ReqTasks_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_ReqTasks_descriptor,
              new java.lang.String[] { });
          internal_static_org_game_protobuf_c2s_SubmitTask_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_org_game_protobuf_c2s_SubmitTask_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_c2s_SubmitTask_descriptor,
              new java.lang.String[] { "TaskCid", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
