// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: S2C/S2CSuccessMsg.proto

package org.game.protobuf.s2c;

public final class S2CSuccessMsg {
  private S2CSuccessMsg() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface OperationSucOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required bool isSuc = 1;
    /**
     * <code>required bool isSuc = 1;</code>
     *
     * <pre>
     * 操作成功
     * </pre>
     */
    boolean hasIsSuc();
    /**
     * <code>required bool isSuc = 1;</code>
     *
     * <pre>
     * 操作成功
     * </pre>
     */
    boolean getIsSuc();
  }
  /**
   * Protobuf type {@code org.game.protobuf.s2c.OperationSuc}
   */
  public static final class OperationSuc extends
      com.google.protobuf.GeneratedMessage
      implements OperationSucOrBuilder {
    // Use OperationSuc.newBuilder() to construct.
    private OperationSuc(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private OperationSuc(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final OperationSuc defaultInstance;
    public static OperationSuc getDefaultInstance() {
      return defaultInstance;
    }

    public OperationSuc getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private OperationSuc(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isSuc_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.game.protobuf.s2c.S2CSuccessMsg.internal_static_org_game_protobuf_s2c_OperationSuc_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.game.protobuf.s2c.S2CSuccessMsg.internal_static_org_game_protobuf_s2c_OperationSuc_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc.class, org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc.Builder.class);
    }

    public static com.google.protobuf.Parser<OperationSuc> PARSER =
        new com.google.protobuf.AbstractParser<OperationSuc>() {
      public OperationSuc parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OperationSuc(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<OperationSuc> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required bool isSuc = 1;
    public static final int ISSUC_FIELD_NUMBER = 1;
    private boolean isSuc_;
    /**
     * <code>required bool isSuc = 1;</code>
     *
     * <pre>
     * 操作成功
     * </pre>
     */
    public boolean hasIsSuc() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bool isSuc = 1;</code>
     *
     * <pre>
     * 操作成功
     * </pre>
     */
    public boolean getIsSuc() {
      return isSuc_;
    }

    private void initFields() {
      isSuc_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasIsSuc()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(1, isSuc_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isSuc_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.game.protobuf.s2c.OperationSuc}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.game.protobuf.s2c.S2CSuccessMsg.OperationSucOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.game.protobuf.s2c.S2CSuccessMsg.internal_static_org_game_protobuf_s2c_OperationSuc_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.game.protobuf.s2c.S2CSuccessMsg.internal_static_org_game_protobuf_s2c_OperationSuc_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc.class, org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc.Builder.class);
      }

      // Construct using org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isSuc_ = false;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.game.protobuf.s2c.S2CSuccessMsg.internal_static_org_game_protobuf_s2c_OperationSuc_descriptor;
      }

      public org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc getDefaultInstanceForType() {
        return org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc.getDefaultInstance();
      }

      public org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc build() {
        org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc buildPartial() {
        org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc result = new org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isSuc_ = isSuc_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc) {
          return mergeFrom((org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc other) {
        if (other == org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc.getDefaultInstance()) return this;
        if (other.hasIsSuc()) {
          setIsSuc(other.getIsSuc());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIsSuc()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.game.protobuf.s2c.S2CSuccessMsg.OperationSuc) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required bool isSuc = 1;
      private boolean isSuc_ ;
      /**
       * <code>required bool isSuc = 1;</code>
       *
       * <pre>
       * 操作成功
       * </pre>
       */
      public boolean hasIsSuc() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bool isSuc = 1;</code>
       *
       * <pre>
       * 操作成功
       * </pre>
       */
      public boolean getIsSuc() {
        return isSuc_;
      }
      /**
       * <code>required bool isSuc = 1;</code>
       *
       * <pre>
       * 操作成功
       * </pre>
       */
      public Builder setIsSuc(boolean value) {
        bitField0_ |= 0x00000001;
        isSuc_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isSuc = 1;</code>
       *
       * <pre>
       * 操作成功
       * </pre>
       */
      public Builder clearIsSuc() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isSuc_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.game.protobuf.s2c.OperationSuc)
    }

    static {
      defaultInstance = new OperationSuc(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:org.game.protobuf.s2c.OperationSuc)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_game_protobuf_s2c_OperationSuc_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_game_protobuf_s2c_OperationSuc_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027S2C/S2CSuccessMsg.proto\022\025org.game.prot" +
      "obuf.s2c\"\035\n\014OperationSuc\022\r\n\005isSuc\030\001 \002(\010B" +
      "\017B\rS2CSuccessMsg"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_game_protobuf_s2c_OperationSuc_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_game_protobuf_s2c_OperationSuc_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_game_protobuf_s2c_OperationSuc_descriptor,
              new java.lang.String[] { "IsSuc", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
